### ISSUE TITLE
vendor/bin/browscap-php browscap:fetch [file] isn't working

### ISSUE THREAD

**Issue by c9s** [browscap/browscap-php#210] opened 2017-05-31 13:17 UTC
```
vendor/bin/browscap-php browscap:fetch a.ini
```

didn't store the a.ini in the current directory.

**Comment by mimmi20** [comment] 2017-06-18 14:59
@c9s I could not verify this. Could you provide more information about the version of `browscap-php` you are using?

**Comment by c9s** [comment] 2017-06-23 11:52
I use this:

```
vendor/bin/browscap-php browscap:fetch a.ini
cat a.ini
```

The cat command should return the content of the file, but the file is not there.

**Comment by asgrim** [comment] 2017-06-24 05:58
@c9s what is the output of the `browscap-php` command please?

**Comment by c9s** [comment] 2017-06-24 05:59
No error message and nothing was printted

**Comment by asgrim** [comment] 2017-06-24 06:04
OK, seems strange. As requested, please could you let us know what *version* of browscap-php you're using?

**Comment by asgrim** [comment] 2017-06-24 06:06
FWIW, I can't reproduce this either using latest `master` at least:

```
$ composer require browscap/browscap-php:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 14 installs, 0 updates, 0 removals
<output removed for brevity>
Writing lock file
Generating autoload files
james@james-xps:~/workspace/test$ vendor/bin/browscap-php browscap:fetch a.ini
[2017-06-24 09:03:47] started fetching remote file {"memory_peak_usage":"2 MB"}
[2017-06-24 09:03:47] there is no cached version available, please update from remote {"memory_peak_usage":"2 MB"}
[2017-06-24 09:03:50] finished fetching remote file {"memory_peak_usage":"28.91 MB"}
james@james-xps:~/workspace/test$ gs
fatal: Not a git repository (or any of the parent directories): .git
james@james-xps:~/workspace/test$ head a.ini 
;;; Provided courtesy of http://browscap.org/
;;; Created on Thursday, May 4, 2017 at 04:07 PM UTC
;;; Keep up with the latest goings-on with the project:
;;; Follow us on Twitter <https://twitter.com/browscap>, or...
;;; Like us on Facebook <https://facebook.com/browscap>, or...
;;; Collaborate on GitHub <https://github.com/browscap>, or...
;;; Discuss on Google Groups <https://groups.google.com/forum/#!forum/browscap>.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Browscap Version
```

**Comment by c9s** [comment] 2017-06-24 06:06
I just followed the instructions described in the readme.

It works fine Through the API, but it seems not working through the commands.

I will retry this in my environment late today.

**Comment by mimmi20** [comment] 2017-08-16 07:16
@c9s Did you install browscpa-php via composer?

**Comment by jakenoble** [comment] 2017-08-23 13:08
Same issue
 
After running `composer require browscap/browscap-php`

There is no file to use in `vendor/bin/browscap-php`

**Comment by mimmi20** [comment] 2017-08-30 13:45
@c9s @jakenoble Which platform do you use? I cannot reproduce this with Linux.

**Comment by jakenoble** [comment] 2017-08-31 12:19
@mimmi20 I have managed to fix it, thanks for your time

**Comment by mimmi20** [comment] 2017-08-31 12:22
@jakenoble I there somthing to fix or to better to explain in the doc?

**Comment by jakenoble** [comment] 2017-08-31 12:24
@mimmi20 Ah no, it was an issue with my host

**Comment by deepakdalakoti** [comment] 2017-10-02 02:48
@jakenoble how did you solve this problem? I am facing similar issue

**Comment by jakenoble** [comment] 2017-10-02 07:38
It was a hosting issue, the php.ini I was changing was not the right one

**Comment by deepakdalakoti** [comment] 2017-10-02 07:43
Your earlier comment says that you didn't have a vendor/bin/browscap-php file. Which php.ini did you change?

**Comment by asgrim** [comment] 2017-12-29 10:47
Closing as nothing useful was added recently, assuming this has been resolved.

**Closed** 2017-12-29 10:47 UTC
Labels: bug, question

**Comment by sweiguny** [comment] 2018-11-23 08:30
i have to warm up the topic...

i am facing the same issue. i was installing the browscap via composer:

    C:\xampp\htdocs\Test>composer require browscap/browscap-php
    Using version ^4.1 for browscap/browscap-php
    [... further composer output ...]
    
    C:\xampp\htdocs\Test>vendor\bin\browscap-php browscap:fetch

    C:\xampp\htdocs\Test>echo Exit Code is %errorlevel%
    Exit Code is 0

so i've got the last version and the fetch script did not throw an error, but it did not output anything at all. i also can't find the fetched file.

what am i doing wrong?
